---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openshop-config
  namespace: openshop
data:
  # Database configurations
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_PROFILES_ACTIVE: "default"
  
  # Service URLs
  USER_SERVICE_URL: "http://user-service:8081"
  PRODUCT_SERVICE_URL: "http://product-service:8082"
  ORDER_SERVICE_URL: "http://order-service:8083"
  PAYMENT_SERVICE_URL: "http://payment-service:8084"
  CART_SERVICE_URL: "http://cart-service:8085"
  INVENTORY_SERVICE_URL: "http://inventory-service:8086"
  SHIPPING_SERVICE_URL: "http://shipping-service:8088"
  
  # Kafka configuration (Strimzi)
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "openshop-kafka-kafka-bootstrap:9092"
  
  # Database hosts
  POSTGRES_USER_HOST: "postgres-user:5432"
  POSTGRES_PRODUCT_HOST: "postgres-product:5432"
  POSTGRES_ORDER_HOST: "postgres-order:5432"
  POSTGRES_CART_HOST: "postgres-cart:5432"
  POSTGRES_INVENTORY_HOST: "postgres-inventory:5432"
  POSTGRES_PAYMENT_HOST: "postgres-payment:5432"
  POSTGRES_NOTIFICATION_HOST: "postgres-notification:5432"
  POSTGRES_SHIPPING_HOST: "postgres-shipping:5432"
